### ISSUE TITLE
Matrikelnummer

### ISSUE THREAD

**Issue by pv42** [pv42/Assignment_DS#2]
Bitte teilt mir eure Matrikelnummer (+Namen) mit !

**Comment by HSporys** [comment]
440347 ( ͡° ͜ʖ ͡°)

**Comment by Sebastian-Neubert** [comment]
445566 ( ͡° ͜ʖ ͡°)

**Comment by HSporys** [comment]
lol ist die matrikelnummer legit, die lässt sich ja mega easy merken

**Comment by Sebastian-Neubert** [comment]
jo na klar is die legit :b
