### ISSUE TITLE
Assignment2

### ISSUE THREAD

**Issue by pv42** [pv42/Assignment_DS#4]
Assignment 2 (https://bildungsportal.sachsen.de/opal/auth/RepositoryEntry/13809057797/CourseNode/95336565331091/Assignments/Assignment02.pdf) enthält im wesentliche folgende Aufgaben:
1.:
-Implementierung einer einfach verketteten Liste
-Implementierung eines Iterators für diese List
-Verwendung dieser List im Zoo sowie des Iterators für Zoorundgänge
2.:
-Implementierung eines Binärbaums
-Implementierung eines Iterators für diesen Baum
-Verwendung dieses Baum im Zoo zur Speicherung der Gehege

Da ich bereits Assignment 1 gemacht habe, könnt ihr euch aussuchen welchen dieser 6 Unteraufgaben ihr machen wollt.

**Comment by Sebastian-Neubert** [comment]
Ich mache 1.3

**Comment by locjul** [comment]
Ich mache Aufgabe 1.1 (Julius)

**Comment by locjul** [comment]
Sorry, meinte Aufgabe 1.1

**Comment by pv42** [comment]
Heinrich: 2.2
SNolte: 1.2

**Comment by pv42** [comment]
Martin 2.3
Clemens 2.1
